name: Scheduled dependencies update
on:
  workflow_dispatch:
    inputs:
      version-type:
        default: patch
        description: Bumps the package version based on value (e.g. patch)
        required: true
      base-branch:
        default: main
        description: Pull request base branch
jobs:
  update-deps:
    name: Bump Node version
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: marcelormourao/gh-action-node-bump-version-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version-type: ${{ github.event.inputs.version-type }}
          base-branch:  ${{ github.event.inputs.base-branch }}